# Obter a lista de agendamento
GET http://localhost:3000/api/agendamento
Content-Type: application/json
###

# Inserir novo agendamento
POST http://localhost:3000/api/agendamento
Content-Type: application/json

{
 "descricao": "teste",
 "data": "2021-01-25T17:32:25.000Z",
  "status": "Concluido",
 "usuario" : "625f54629c8371e4b4f75ffd",
  "maquina" : "625f4cf7397d2e40cc315f5e"
}

###
# Alterar agendamento
PUT http://localhost:3000/api/agendamento
Content-Type: application/json

{
 "_id": "623a564f28f3d465d3c9150a",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com",
 "celular": "54 6543 2423"

}
###

# Excluir um agendamento
DELETE http://localhost:3000/api/agendamento/625f54979c8371e4b4f76006

Content-Type: application/json
###
# Obter pelo id de agendamento
GET http://localhost:3000/api/agendamento/623a566628f3d465d3c9150c
Content-Type: application/json
###
# Obter agendamento filtrando
GET http://localhost:3000/api/agendamento/filtro/fulano
Content-Type: application/json
###










